# C3D4: Channel Flow Variational - Cranfield HPC Deployment
# 3D Track Experiment - Variational inference for uncertainty quantification

experiment_id: C3D4_channel_primary_final_1000
description: "Channel flow variational model - Cranfield HPC deployment (1200 cubes at 96³ resolution)"

# Dataset configuration - UPDATED FOR CRANFIELD
dataset:
  name: channel3d
  data_dir: /home/USERNAME/data/channel_flow_1000/jhtdb_96cubed_production_structured
  resolution: [96, 96, 96]
  variables: [u, v, w]  # velocity components only
  y_plus_range: [0, 1000]  # Full Y+ range for primary dataset
  normalization: channel_stats
  
# Model architecture (3D Variational U-Net)
model:
  name: unet3d_variational
  in_channels: 3  # u, v, w only
  out_channels: 3
  base_channels: 32
  depth: 4
  dropout: 0.0  # No dropout for variational
  batch_norm: true
  activation: relu
  kl_weight: 0.0000001  # Starting KL weight (1e-7) - will warm up to 6e-7 over 30 epochs

# Uncertainty quantification
uq:
  method: variational
  
# Training configuration
train:
  batch_size: 2
  epochs: 200
  lr: 0.0001
  weight_decay: 0.0001
  optimizer: adam
  scheduler: cosine
  num_workers: 4
  amp: true
  early_stopping:
    patience: 20
    min_delta: 0.000001
    
# Loss function
loss:
  name: variational_elbo
  reduction: mean
  
# Data loading
dataloader:
  pin_memory: true
  persistent_workers: true
  
# Validation
validation:
  frequency: 5
  metrics: [rmse, mae, r2, kl_divergence, elbo]
  
# Paths - UPDATED FOR CRANFIELD HPC
paths:
  artifacts_root: /home/USERNAME/artifacts_3d
  results_dir: /home/USERNAME/artifacts_3d/results/C3D4_channel_primary_final_1000
  checkpoints_dir: /home/USERNAME/artifacts_3d/checkpoints/C3D4_channel_primary_final_1000
  logs_dir: /home/USERNAME/artifacts_3d/logs/training
  cache_dir: /home/USERNAME/artifacts_3d/cache
  
# Hardware
device: cuda
mixed_precision: true
gradient_checkpointing: true

# Reproducibility
seed: 42
deterministic: true
