# C3D3: Channel Flow Ensemble - Primary Final Dataset (Re_τ=1000)
# 3D Track Experiment - Deep Ensemble for uncertainty quantification

experiment_id: C3D3_channel_primary_final_1000
description: "Channel flow ensemble model - Primary final dataset 1200 cubes at 96³ resolution"

# Dataset configuration
dataset:
  name: channel3d
  data_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/data_3d/channel_flow_1000
  resolution: [96, 96, 96]
  variables: [u, v, w]  # velocity components only
  y_plus_range: [0, 1000]  # Full Y+ range for primary dataset
  normalization: channel_stats
  
# Model architecture (3D U-Net Ensemble)
model:
  name: unet3d_ensemble
  in_channels: 3  # u, v, w only
  out_channels: 3
  base_channels: 32
  depth: 4
  dropout: 0.0  # No dropout for ensemble
  batch_norm: true
  activation: relu
  ensemble_size: 5  # Number of ensemble members

# Uncertainty quantification
uq:
  method: ensemble
  ensemble_members: 5
  
# Training configuration
train:
  batch_size: 2
  epochs: 200
  lr: 0.0001
  weight_decay: 0.0001
  optimizer: adam
  scheduler: cosine
  num_workers: 4
  amp: true
  early_stopping:
    patience: 20
    min_delta: 0.000001
    
# Loss function
loss:
  name: mse
  reduction: mean
  
# Data loading
dataloader:
  pin_memory: true
  persistent_workers: true
  
# Validation
validation:
  frequency: 5
  metrics: [rmse, mae, r2, ensemble_variance]
  
# Paths (3D track artifacts)
paths:
  artifacts_root: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d
  results_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/results/C3D3_channel_primary_final_1000
  checkpoints_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/checkpoints/C3D3_channel_primary_final_1000
  logs_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/logs/training
  cache_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/cache
  
# Hardware
device: cuda
mixed_precision: true
gradient_checkpointing: true

# Reproducibility
seed: 42
deterministic: false  # Different seeds for ensemble members
