# C3D6: Channel Flow Physics-Informed - Primary Final Dataset (Re_τ=1000)
# 3D Track Experiment - Physics-informed neural network with uncertainty quantification

experiment_id: C3D6_channel_primary_final_1000
description: "Channel flow physics-informed model - Primary final dataset 1200 cubes at 96³ resolution"

# Dataset configuration
dataset:
  name: channel3d
  data_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/data_3d/channel_flow_1000
  resolution: [96, 96, 96]
  variables: [u, v, w]  # velocity components only
  y_plus_range: [0, 1000]  # Full Y+ range for primary dataset
  normalization: channel_stats
  
# Model architecture (3D U-Net with Physics-Informed Training)
model:
  name: unet3d
  in_channels: 3
  out_channels: 3
  base_channels: 32
  depth: 4
  dropout: 0.1  # Light dropout for regularization
  batch_norm: true
  activation: relu
  physics_weight: 0.1  # Physics loss weight
  
# Training configuration
train:
  batch_size: 2
  epochs: 200
  lr: 0.0001
  weight_decay: 0.0001
  optimizer: adam
  scheduler: cosine
  num_workers: 4
  loss: physics_informed
  early_stop_patience: 20
  save_every: 5
  amp: true
  physics_weight: 0.1
  continuity_weight: 0.05
  momentum_weight: 0.05
  
# Paths (3D track artifacts)
paths:
  artifacts_root: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d
  results_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/results/C3D6_channel_primary_final_1000
  checkpoints_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/checkpoints/C3D6_channel_primary_final_1000
  logs_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/logs/training
  cache_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/cache
  
# Hardware
device: cuda
mixed_precision: true
gradient_checkpointing: true

# Uncertainty Quantification (physics-informed with dropout)
uq:
  method: physics_informed
  dropout_p: 0.1

# Reproducibility
seed: 42
deterministic: true
