experiment_id: E6_hit_ab_ens
seed: 42

paths:
  data_root: data/raw/hit
  velocity_h5: data/raw/hit/hit_velocity.h5
  pressure_h5: data/raw/hit/hit_pressure.h5
  splits_dir: splits
  results_dir: results
  experiments_manifest: experiments/manifest.csv

data:
  velocity_key: Velocity_0001
  pressure_key: Pressure_0001
  input_fields: [velocity]
  target_fields: [pressure]
  block_size: 32
  stride: 32
  normalisation: per_channel_z
  eval_stride: 1

splits:
  strategy: contiguous_xyz_ab
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

model:
  backbone: unet3d
  in_channels: 3
  out_channels: 1
  base_channels: 32
  spectral_loss: false
  spectral_weight: 0.0

uq:
  method: ensemble
  ensemble_members: 5
  dropout_p: 0.20

train:
  loss: mse
  epochs: 1
  batch_size: 1
  num_workers: 0
  lr: 3.0e-4
  weight_decay: 1.0e-2
  amp: false
  early_stop_patience: 10
  save_every: 1

eval:
  mc_samples: 32
  metrics: [rmse, mae, nll, crps, coverage90, coverage95, ece, aurc, spearman_rho, spectral_error]
  save_predictions: true
