# C3D5: Channel Flow SWAG - Primary Dataset (Re_τ=1000)
# 3D Track Experiment - Stochastic Weight Averaging Gaussian for uncertainty quantification

experiment_id: C3D5_channel_primary_1000
description: "Channel flow SWAG model - Primary dataset 1600 cubes at 96³ resolution"

# Dataset configuration
dataset:
  name: channel3d
  data_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/data_3d/channel_flow_1000/jhtdb_96cubed_production_structured
  resolution: [96, 96, 96]
  variables: [u, v, w]  # velocity components only
  y_plus_range: [5, 800]  # Primary dataset Y+ range
  normalization: channel_stats
  
# Model architecture (3D U-Net with SWAG)
model:
  name: unet3d
  in_channels: 3
  out_channels: 3
  base_channels: 32
  depth: 4
  dropout: 0.0  # No dropout for SWAG
  batch_norm: true
  activation: relu
  swag_start: 100  # Start SWAG collection at epoch 100
  swag_lr: 0.00001   # SWAG learning rate
  swag_c_epochs: 1  # Collect every epoch
  
# Training configuration
train:
  batch_size: 2
  epochs: 200
  lr: 0.00001
  weight_decay: 0.00001
  optimizer: adam
  scheduler: cosine
  num_workers: 4
  loss: mse
  early_stop_patience: 20
  save_every: 5
  amp: true
  
# Paths (3D track artifacts)
paths:
  artifacts_root: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d
  results_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/results/C3D5_channel_primary_1000
  checkpoints_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/checkpoints/C3D5_channel_primary_1000
  logs_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/logs/training
  cache_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/cache
  
# Hardware
device: cuda

# Reproducibility
seed: 42
