# C3D2: Channel Flow MC Dropout - 128³ Resolution
# 3D Track Experiment - MC Dropout for uncertainty quantification

experiment_id: C3D2_channel_mc_dropout_128
description: "Channel flow MC Dropout model at 128³ resolution"

# Dataset configuration
dataset:
  name: channel3d
  data_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/data_3d/channel_flow_smoke
  resolution: [64, 64, 64]
  variables: [u, v, w]  # velocity components only
  y_plus_range: [0.5, 1000]
  normalization: channel_stats
  
# Model architecture (3D U-Net with Dropout)
model:
  name: unet3d_dropout
  in_channels: 3
  out_channels: 3
  base_channels: 32
  depth: 4
  dropout: 0.1  # MC Dropout rate
  batch_norm: true
  activation: relu
  mc_samples: 100  # Number of MC forward passes

# Uncertainty quantification
uq:
  method: mc_dropout
  samples: 100
  dropout_p: 0.1
  
# Training configuration
train:
  batch_size: 2
  epochs: 200
  lr: 0.0001
  weight_decay: 0.0001
  optimizer: adam
  scheduler: cosine
  num_workers: 4
  amp: true
  early_stopping:
    patience: 20
    min_delta: 0.000001
    
# Loss function
loss:
  name: mse
  reduction: mean
  
# Data loading
dataloader:
  pin_memory: true
  persistent_workers: true
  
# Validation
validation:
  frequency: 5
  metrics: [rmse, mae, r2, nll, coverage]

# Evaluation configuration
eval:
  mc_samples: 100
  temperature_scale: false
  conformal: false
  
# Paths (3D track artifacts)
paths:
  artifacts_root: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d
  results_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/results/C3D2_channel_mc_dropout_128
  checkpoints_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/checkpoints/C3D2_channel_mc_dropout_128
  logs_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/logs/training
  cache_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/cache
  
# Hardware
device: cuda
mixed_precision: true
gradient_checkpointing: true

# Reproducibility
seed: 42
deterministic: true
