# C3D6: Channel Flow Physics-Informed - 128³ Resolution
# 3D Track Experiment - Physics-informed neural network with uncertainty quantification

experiment_id: C3D6_channel_physics_informed_128
description: "Channel flow physics-informed model at 128³ resolution"

# Dataset configuration
dataset:
  name: channel3d
  data_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/data_3d/channel_flow_smoke
  resolution: [64, 64, 64]
  variables: [u, v, w]  # velocity components only
  y_plus_range: [0.5, 1000]
  normalization: channel_stats
  
# Model architecture (3D U-Net with Physics-Informed Training)
model:
  name: unet3d
  in_channels: 3
  out_channels: 3
  base_channels: 32
  depth: 4
  dropout: 0.1  # Light dropout for regularization
  batch_norm: true
  activation: relu
  physics_weight: 0.1  # Physics loss weight
  
# Training configuration
train:
  batch_size: 2
  epochs: 200
  lr: 0.0001
  weight_decay: 0.0001
  optimizer: adam
  scheduler: cosine
  num_workers: 4
  loss: physics_informed
  early_stop_patience: 20
  save_every: 5
  amp: true
  physics_weight: 0.1
  continuity_weight: 0.05
  momentum_weight: 0.05
  
# Paths (3D track artifacts)
paths:
  artifacts_root: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d
  results_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/results/C3D6_channel_physics_informed_128
  checkpoints_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/checkpoints/C3D6_channel_physics_informed_128
  logs_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/logs/training
  cache_dir: /mnt/iusers01/fse-ugpgt01/mace01/p78669sb/artifacts_3d/cache
  
# Hardware
device: cuda

# Reproducibility
seed: 42
